export const DOM = {
  btnMenu: document.querySelectorAll(".button-menu"),
  menu: document.querySelector(".menu"),
  section: document.querySelectorAll(".section"),
  buttonHome: document.querySelector(".button-home"),
  sectionGirls: document.querySelector(".section-girls"),
  sectionGirlPerfil: document.querySelector(".section-girl-perfil"),
  girlBanner: document.querySelector(".girl-perfil-banner"),
  girlImg: document.querySelector(".girl-perfil-img"),
  girlName: document.querySelector(".girl-perfil-name"),
  girlTags: document.querySelector(".girl-perfil-tags"),
  girlAmount: document.querySelector(".girl-perfil-amount"),
  buttonGirlPerfilPhotos: document.querySelector(".button-girl-perfil-photos"),
  buttonGirlPerfilVideos: document.querySelector(".button-girl-perfil-videos"),
  girlPhotos: document.querySelector(".girl-perfil-photos"),
  girlVideos: document.querySelector(".girl-perfil-videos"),
};
